version: 2.1
orbs:
  node: circleci/node@5.1.0
  secops: apollo/circleci-secops-orb@2.0.0
workflows:
  node-tests:
    jobs:
      - node/test:
          version: 18.15.0
  security-scans:
    jobs:
      - secops/gitleaks:
          context:
            - platform-docker-ro
            - github-orb
            - secops-oidc
          git-base-revision: <<#pipeline.git.base_revision>><<pipeline.git.base_revision>><</pipeline.git.base_revision >>
          git-revision: << pipeline.git.revision >>
